### ISSUE TITLE
Light not showing in Home Assistant integrations

### ISSUE THREAD

**Issue by ghost** [pinkywafer/PinkyLEDs#10]
Home Assistant uses Integrations now for auto discovered devices. 
The Discovery in the PinkyLEDs script seems to work as far as the light being available, but it never shows in the MQTT Integrations in Home Assistant.  
I've tried everything I can think of on the Home Assistant side of things, but have not been able to get it to work.  
The information I have indicates that maybe the unique_id may not be populated, but I have found little information to confirm this.
The light works, it shows up as an entity, it just never shows in Integrations.
Can you assist further?

**Comment by pinkywafer** [comment]
Thanks - can you please try the version of PinkyLEDs.ino that is in the `discovery_patch` branch.

**Comment by ghost** [comment]
So quick off the mark with this one :).   The `discovery_patch` branch seems to have fixed the issue mostly.
It shows in integrations, but shows as entities without devices.

**Comment by pinkywafer** [comment]
Thanks, I'll make another quick edit so that the integration shows up as PinkyLED_DEVICE_NAME then merge back to master
