### ISSUE TITLE
Integration shows "No Entities"

### ISSUE THREAD

**Issue by ghost** [pinkywafer/PinkyLEDs#12]
Sorry to throw another one at you for the Discovery.

It turns out one more option is needed for it to show as an entity and allow an "Area" to be assigned in integrations.

This needs to be added to the DISCOVERY_BASE directly after unique_id

`\"device\":{\"identifiers\":\"" DEVICE_NAME "\",\"model\":\"generic\",\"manufacturer\":\"PinkyWafer\",\"name\":\"" DEVICE_NAME "\"},`

That's what I used, obviously can use whatever you like to describe it.   Most settings are optional, but it needs at minimum device: identifiers  to show.

I was wondering why TASMOTA showed more details in it , so I had a look at the MQTT discovery topic from tasmota and found the device information.
I got the information from https://www.home-assistant.io/components/light.mqtt/

Thanks :)

Edit: the Model and the Manufacturer show in the Integration page.

**Comment by pinkywafer** [comment]
Thanks for this.. I'll do a quick edit for this again!.

**Comment by ghost** [comment]
Until the next breaking change in HA :)

**Comment by pinkywafer** [comment]
yeah - Keeping us all on our toes!!

**Comment by pinkywafer** [comment]
Added to master!

**Comment by ghost** [comment]
Thanks.  Hopefully that is all now for this version of HA :)

Appreciate all your hard work.
