### ISSUE TITLE
Control via rotary encoder

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/PinkyLEDs#2]
Based on a request from DrZzs,
Allow use of rotary encoder to adjust brightness and animation speed
Could also be used for effect and color

**Comment by teslahed** [comment]
I like the idea of manual brightness control as a feature, be it via rotary encoder, buttons or a potentiometer. If the analogue input is free then a potentiometer is a nice way to control brightness that I have used in other simpler projects.

**Comment by pinkywafer** [comment]
I think I'm going to avoid a pot because a pot would give a value, and if the brightness value is then changed via mqtt, there is no way to make the pot match, which may end up (for example) with the light at one brightness,  and the pot at another,  whereas with a rotary encoder,  we are simply adjusting up or down.

I have now got some encoders, so I'll have a go at this when I get chance
