### ISSUE TITLE
Invalid pin assignments on esp8266 board

### ISSUE THREAD

**Issue by Beachviolence** [pinkywafer/PinkyLEDs#3]
Hi. Im having a really bad time compiling this because i don't know what versions of the includes you use. Got most of my compiling errors away be downgrading some packages, but some wont go away. Would be great if you included them in the README :) My error log:

> 

```
In file included from C:\Users\pc\Documents\Arduino\portable\sketchbook\libraries\FastLED/FastLED.h:48:0,

                 from C:\Users\pc\OneDrive\Dokumenter\Hassio\LED\PinkyLEDs-master\PinkyLEDs\PinkyLEDs.ino:7:

C:\Users\pc\Documents\Arduino\portable\sketchbook\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<14u>':

C:\Users\pc\Documents\Arduino\portable\sketchbook\libraries\FastLED/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<14, 20, 50, 30, (EOrder)66u, 0, false, 50>'

C:\Users\pc\Documents\Arduino\portable\sketchbook\libraries\FastLED/chipsets.h:550:7:   required from 'class WS2812Controller800Khz<14u, (EOrder)66u>'

C:\Users\pc\Documents\Arduino\portable\sketchbook\libraries\FastLED/FastLED.h:103:52:   required from 'class WS2812<14u, (EOrder)66u>'

C:\Users\pc\Documents\Arduino\portable\sketchbook\libraries\FastLED/FastLED.h:302:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812; unsigned char D5 = 14u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\pc\OneDrive\Dokumenter\Hassio\LED\PinkyLEDs-master\PinkyLEDs\PinkyLEDs.ino:233:66:   required from here

C:\Users\pc\Documents\Arduino\portable\sketchbook\libraries\FastLED/fastpin.h:207:2: error: static assertion failed: Invalid pin specified

  static_assert(validpin(), "Invalid pin specified");
```

>

**Comment by pinkywafer** [comment]
Currently using:
FastLED version 3.1+ (I'm currently using 3.2.6)
ArduinoJson version 5  (I'm using version 5.13.5) (migration to version 6 not yet complete)
PubSubClient version 2.7
ESPAsyncE131 version 1.0

Though looking at your error log, I have a feeling you may be using a different board to me.  I've designed for Wemos D1 R1, so other modifications may be needed for other boards

**Comment by Beachviolence** [comment]
Ahh that explains it! Yes, im using ESP8266. Thanks, ill use my D1 instead.

**Comment by pinkywafer** [comment]
OK.  You may still be able to use the ESP8266, but at the least, you'd have to change the pin assignments, as I believe they are exposed differently in the library

**Comment by Beachviolence** [comment]
I figured out what caused the error. For some reason, the program got 

> expected > before numeric constant

 when the `#define DATA_PIN 5` was in the header file (i have to use 5, not D5 on the NodeMCU 1.0). I moved the header to the .ino file, and everything compiled successfully. Don't know if this helps, but sometimes the fix is just weird in C++ i guess. 

Thanks for sharing your code!

[The code with my fix](https://github.com/Beachviolence/PinkyLEDs)

**Comment by pinkywafer** [comment]
Thanks... suddenly this makes sense... 
I think with the #define in the header, D5 is evaluated as a compiler variable for the D1 board so the compiler actually uses GPIO14, whereas using 5 does not translate.

It may be worth trying the define in the header, but with one of 
```
#define FASTLED_ESP8266_RAW_PIN_ORDER
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER
#define FASTLED_ESP8266_D1_PIN_ORDER
```
Also in the header file..

See https://github.com/FastLED/FastLED/wiki/ESP8266-notes

**Comment by pinkywafer** [comment]
In fact... just moving the include for config.h below the other includes may also solve the issue.  I'll do some testing tomorrow!

**Comment by pinkywafer** [comment]
Yep... got it.  The fastLED include needs to be before the config.h include.
updating now!
