### ISSUE TITLE
fatal error when compiling

### ISSUE THREAD

**Issue by mszymura** [pinkywafer/PinkyLEDs#5]
hi, every time i try and compile i get this error
ESPAsyncE131.h:23:25: fatal error: ESPAsyncUDP.h: No such file or directory

 #include <ESPAsyncUDP.h>
I have included the ESPAsynchE131 library v1 as shown but it wants to reference this file which isnt in the library. Using all the libraries as suggested.
thanks,

**Comment by pinkywafer** [comment]
My apologies,  this should be on the list of dependancies... the ESPAsyncUDP library is a required by the ESPAsync131 library. 

I'll update readme to include this library
