### ISSUE TITLE
Last will (LWT) message problem

### ISSUE THREAD

**Issue by bbacskay** [pinkywafer/PinkyLEDs#6]
Within the reconnect() function the program connects to the MQTT broker setting the LWT message "Offline" as non-retain (the second 0 parameter of the client.connect), but then the program publishes the "Online" message as retain.
The result of the disconnection is when another MQTT client is subscribed to the LWT topic it receives correctly the "Offline" message, but if the same client reconnects while the PinkyLED device is still unreachable then it would receive the "Online" message on reconnection since that was the last retained message of that topic.

The fix is easy change the second 0 parameter in the connect function to true or 1.

**Comment by pinkywafer** [comment]
Thanks. I'll get to this!
