### ISSUE TITLE
dots

### ISSUE THREAD

**Issue by mszymura** [pinkywafer/PinkyLEDs#7]
Hi,
got the pinkyleds up and running and they are stunning , thank you. just one issue, I noticed on the Dots effects it only works for half the length . I have 3 x 5 m (150) leds connected and all the other effects work great. 
Not a big deal but thought I would mention it.
once again, thank you

**Comment by pinkywafer** [comment]
Do the other effects work as expected?

**Comment by mszymura** [comment]
hi Jenny,
yep, all are great, just the dots for some reason. thanks for the reply
Mark

**Comment by pinkywafer** [comment]
Thanks,  I'll see if I can find anything amiss in the dots code

**Comment by bbacskay** [comment]
Hi mszymura,

do you have 150 leds altogether in the 3 stripes or 450?

**Comment by mszymura** [comment]
Hi
450 all together injecting power ever 150 
Ta
