### ISSUE TITLE
State Topic Message Problem

### ISSUE THREAD

**Issue by delta010** [pinkywafer/PinkyLEDs#8]
"stat/" DEVICE_NAME  is not working .nothing happened when the LED change its state.

**Comment by pinkywafer** [comment]
Can you give any more information please?   This seems to be working for others. I'm guessing this is going to be related to the connection to your broker. When powering on, do the leds flash red, Amber and green?  Red indicates power on.. Amber...  Wi-Fi connected,  green mqtt connected

**Comment by delta010** [comment]
I am using NodeMCU, rather then Home Assistant I use Node-Red to control the LEDs.The "cmnd/PinkyLEDs" topic work fine But the "stat/PinkyLEDs" is not working,  there is no status message

**Comment by pinkywafer** [comment]
If you are using cmnd/PinkyLEDs, by default,  that is the group command topic. There is no group status message. As default config, the status topic would be cmnd/PinkyLED1

The group topic is intended to allow you to control a collection of nodes at the same time with only 1 command

**Comment by delta010** [comment]
so there is no power on/off status

**Comment by pinkywafer** [comment]
The status message is only published for the individual node, so with the default config:
Node status topic:
`stat/PinkyLED1`
node command topic
`cmnd/PinkyLED1`
Group command topic (for controlling multiple nodes):
`cmnd/PinkyLEDs`

The messages are all json format. Commands can contain just the command required,  but the status will contain all current information (except flash which is omitted when off)

The current state is always the first part of the json message:  `"state": "OFF" `
