### ISSUE TITLE
Animation speed slider scale

### ISSUE THREAD

**Issue by tinimark** [pinkywafer/PinkyLEDs#9]
This is my goto code for controlling LEDs from HA. Thanks!
I'm trying to change the scaling for the animation speed (white_value) slider because it's difficult to get the speed I want.
I tried root[SPEEDTOPIC] = map(animationspeed,0,255,200,255);
but that didn't work. 
Can't seem to change the slider scale within HA either.
Any ideas?

**Comment by pinkywafer** [comment]
If you're using the white_value option, there is the white_value_scale or white_value_template options available in the HA light config,  but I haven't tried setting them up

**Comment by tinimark** [comment]
From what I can work out, white_value_scale can only define a percentage of the full scale. What I have found is the animation speeds that are of most use are at the very end of the slider if that makes sense

**Comment by pinkywafer** [comment]
In the callback function,  you could try:
```
animationspeed = root[SPEEDTOPIC];
animationspeed = map(animationspeed,0,255,200,255);
```
And, you would also need
```
root[SPEEDTOPIC] = map(animationspeed,200,255,0,255);
```
In the publishState function

**Comment by tinimark** [comment]
Thankyou :)
